#!groovy
import groovy.json.JsonBuilder

def attachmentPayload = [[
    fallback: "execution #${env.BUILD_NUMBER}",
    color: "#2eb886",
    pretext: "${env.JOB_NAME}",
    text: "DEPLOY DONE #${env.BUILD_NUMBER}",
]]

pipeline {
    agent {
        label 'master'
    }
    environment {
        mysqlserver = "${MYSQL_SERVER}"
        mysqlpassword = "${MYSQL_PASSWORD}"
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'osdn/slash-build'
                    args '-e BRANCH_NAME=${BRANCH_NAME} -e MYSQL_SERVER=${mysqlserver} -e MYSQL_PASSWORD=${mysqlpassword}'
                }
            }
            steps {
                sh 'rm -rf RestServiceSample'
                sh 'git clone https://github.com/cutem-0104/RestServiceSample.git'
                //sh 'cd RestServiceSample && git checkout ${params.BRANCH_NAME} && gradle war'
                sh 'cd RestServiceSample && git checkout ${BRANCH_NAME} && gradle war'
            }
        }
        stage('Deploy') {
            agent {
                label 'master'
            }
            steps {
                sh 'sudo cp /var/lib/jenkins/workspace/slash-build-build/RestServiceSample/build/libs/*.war /home/cutem/rest-app/Docker/tomcat/target/war/ROOT.war'
                sh 'cd /home/cutem/rest-app/Docker && sudo docker-compose down'
                sh 'cd /home/cutem/rest-app/Docker && sudo docker-compose up -d  -e MYSQL_SERVER=${mysqlserver} -e MYSQL_PASSWORD=${mysqlpassword}'
                sh 'curl -L http://153.127.14.75/greeting'
            }
        }
    }
    post {
        always {
            echo 'DEPLOY DONE'
            script {// ここだけscripted pipeline のsyntaxを適用する
                slackSend(channel: '#sugaya_github_bot', color: "#2eb886", attachments: new JsonBuilder(attachmentPayload).toString())
            }
        }
    }
}
